# Generated by Django 3.1.2 on 2023-06-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='porcentaje',
        ),
    ]
