# Generated by Django 3.1.2 on 2023-07-03 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estado_seguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrito')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('nombreEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
            ],
        ),
    ]
