# Generated by Django 3.1.2 on 2023-07-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
