# Generated by Django 3.1.2 on 2023-07-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_seguimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
