# Generated by Django 3.1.2 on 2023-07-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_suscripcion_monto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
