# Generated by Django 3.1.2 on 2023-07-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='carrito',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
